### ISSUE TITLE
Laravel 10 compatibility

### ISSUE THREAD

**Issue by saschagysel** [codeat3/blade-fluentui-system-icons#57]
Hey, looking forward to a Laravel 10 compatibility update so. Do you already have a plan for this? Thanks.

**Comment by inkomomutane** [comment]
same  issue here!

**Comment by swapnilsarwe** [comment]
Hey @saschagysel ,
Kindly update the package to `1.32.1` to have laravel 10 support.
Thanks @inkomomutane for the PR.
